#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update -y
sudo apt-get install haproxy -y

echo "
frontend mamurofocus
	bind *:80
	default_backend focusmamuro

backend focusmamuro
	balance roundrobin
	server 144137-web-01 100.26.235.127:80 check
    server 144137-web-02 100.27.13.117:80 check	
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
