#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine
interfaces=$(ifconfig | grep -w inet | awk '{print $1}')
for interface in $interfaces
do
    ip=$(ifconfig $interface | grep -w inet | awk '{print $2}')
    if [ ! -z "$ip" ]; then
        echo "$interface: $ip"
    fi
done
