#!/usr/bin/env bash
# configures nginx as user

# stop nginx
sudo service nginx stop

# change the user to nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# change ownership of nginx
chmod 644 /etc/nginx/nginx.conf

# change nginx listening port from 80 to port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# stop apache from interferring
pkill apache2

# Start nginx
sudo -u nginx service nginx start
